#use_frameworks!
source 'https://gitee.com/zhenlove/zhenSpecs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

target 'KMRouter-Example' do

  pod 'KMConfigure', :path => './KMConfigure/'
  pod 'KMRouter', :path => '../'
#  pod 'KMRouter', :git=>'https://github.com/zhenlove/KMRouter.git'
  pod 'KMModuleA', :path => './KMModuleA/'
  pod 'KMModuleB', :path => './KMModuleB/'
  pod 'KMModuleC', :path => './KMModuleC/',:modular_headers => true
  pod 'KMModuleD', :path => './KMModuleD/',:modular_headers => true


end
